sudo: required
language: java
jdk:
  - openjdk11
branches:
 only:
  - master
before_install:
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar
install: ./gradlew clean build
script: ./gradlew test jacocoTestReport jacocoFullReport
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/report.xml
